baseURL = "/"
languageCode = "en-us"
title = "Selwyn's Site"
theme = "kube"
description = "blog"
Paginate = 10
[Params]
  RSSLink = "/index.xml"
  author = "Selwyn Shen" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "selwynshen@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
